/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LoadWhereUniqueInput } from "../../load/base/LoadWhereUniqueInput";
import { NegotiationWhereUniqueInput } from "../../negotiation/base/NegotiationWhereUniqueInput";
import { EnumAssignmentStatus } from "./EnumAssignmentStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class AssignmentWhereInput {
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  finalAmount?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LoadWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LoadWhereUniqueInput)
  @IsOptional()
  @Field(() => LoadWhereUniqueInput, {
    nullable: true,
  })
  load?: LoadWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => NegotiationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => NegotiationWhereUniqueInput)
  @IsOptional()
  @Field(() => NegotiationWhereUniqueInput, {
    nullable: true,
  })
  negotiation?: NegotiationWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumAssignmentStatus,
  })
  @IsEnum(EnumAssignmentStatus)
  @IsOptional()
  @Field(() => EnumAssignmentStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { AssignmentWhereInput as AssignmentWhereInput };
