/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentUpdateManyWithoutUsersInput } from "./AssignmentUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { LoadUpdateManyWithoutUsersInput } from "./LoadUpdateManyWithoutUsersInput";
import { NegotiationUpdateManyWithoutUsersInput } from "./NegotiationUpdateManyWithoutUsersInput";
import { EnumUserRoleType } from "./EnumUserRoleType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AssignmentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AssignmentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  assignments?: AssignmentUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LoadUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LoadUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LoadUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  loads?: LoadUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => NegotiationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => NegotiationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => NegotiationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  negotiations?: NegotiationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleType,
  })
  @IsEnum(EnumUserRoleType)
  @IsOptional()
  @Field(() => EnumUserRoleType, {
    nullable: true,
  })
  roleType?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
