/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentListRelationFilter } from "../../assignment/base/AssignmentListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { LoadListRelationFilter } from "../../load/base/LoadListRelationFilter";
import { NegotiationListRelationFilter } from "../../negotiation/base/NegotiationListRelationFilter";
import { EnumUserRoleType } from "./EnumUserRoleType";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AssignmentListRelationFilter)
  @IsOptional()
  @Field(() => AssignmentListRelationFilter, {
    nullable: true,
  })
  assignments?: AssignmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  companyName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LoadListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LoadListRelationFilter)
  @IsOptional()
  @Field(() => LoadListRelationFilter, {
    nullable: true,
  })
  loads?: LoadListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => NegotiationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NegotiationListRelationFilter)
  @IsOptional()
  @Field(() => NegotiationListRelationFilter, {
    nullable: true,
  })
  negotiations?: NegotiationListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  phoneNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleType,
  })
  @IsEnum(EnumUserRoleType)
  @IsOptional()
  @Field(() => EnumUserRoleType, {
    nullable: true,
  })
  roleType?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
