/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentCreateNestedManyWithoutUsersInput } from "./AssignmentCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { LoadCreateNestedManyWithoutUsersInput } from "./LoadCreateNestedManyWithoutUsersInput";
import { NegotiationCreateNestedManyWithoutUsersInput } from "./NegotiationCreateNestedManyWithoutUsersInput";
import { EnumUserRoleType } from "./EnumUserRoleType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AssignmentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AssignmentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  assignments?: AssignmentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LoadCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LoadCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LoadCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  loads?: LoadCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => NegotiationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => NegotiationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => NegotiationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  negotiations?: NegotiationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleType,
  })
  @IsEnum(EnumUserRoleType)
  @IsOptional()
  @Field(() => EnumUserRoleType, {
    nullable: true,
  })
  roleType?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
