/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Load as PrismaLoad,
  Assignment as PrismaAssignment,
  Negotiation as PrismaNegotiation,
  User as PrismaUser,
} from "@prisma/client";

export class LoadServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.LoadCountArgs, "select">): Promise<number> {
    return this.prisma.load.count(args);
  }

  async loads(args: Prisma.LoadFindManyArgs): Promise<PrismaLoad[]> {
    return this.prisma.load.findMany(args);
  }
  async load(args: Prisma.LoadFindUniqueArgs): Promise<PrismaLoad | null> {
    return this.prisma.load.findUnique(args);
  }
  async createLoad(args: Prisma.LoadCreateArgs): Promise<PrismaLoad> {
    return this.prisma.load.create(args);
  }
  async updateLoad(args: Prisma.LoadUpdateArgs): Promise<PrismaLoad> {
    return this.prisma.load.update(args);
  }
  async deleteLoad(args: Prisma.LoadDeleteArgs): Promise<PrismaLoad> {
    return this.prisma.load.delete(args);
  }

  async findAssignments(
    parentId: string,
    args: Prisma.AssignmentFindManyArgs
  ): Promise<PrismaAssignment[]> {
    return this.prisma.load
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .assignments(args);
  }

  async findNegotiations(
    parentId: string,
    args: Prisma.NegotiationFindManyArgs
  ): Promise<PrismaNegotiation[]> {
    return this.prisma.load
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .negotiations(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.load
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
