/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentCreateNestedManyWithoutLoadsInput } from "./AssignmentCreateNestedManyWithoutLoadsInput";

import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { NegotiationCreateNestedManyWithoutLoadsInput } from "./NegotiationCreateNestedManyWithoutLoadsInput";
import { EnumLoadStatus } from "./EnumLoadStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class LoadCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentCreateNestedManyWithoutLoadsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentCreateNestedManyWithoutLoadsInput)
  @IsOptional()
  @Field(() => AssignmentCreateNestedManyWithoutLoadsInput, {
    nullable: true,
  })
  assignments?: AssignmentCreateNestedManyWithoutLoadsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deliveryDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destination?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  details?: string | null;

  @ApiProperty({
    required: false,
    type: () => NegotiationCreateNestedManyWithoutLoadsInput,
  })
  @ValidateNested()
  @Type(() => NegotiationCreateNestedManyWithoutLoadsInput)
  @IsOptional()
  @Field(() => NegotiationCreateNestedManyWithoutLoadsInput, {
    nullable: true,
  })
  negotiations?: NegotiationCreateNestedManyWithoutLoadsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  origin?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  pickupDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumLoadStatus,
  })
  @IsEnum(EnumLoadStatus)
  @IsOptional()
  @Field(() => EnumLoadStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  weight?: number | null;
}

export { LoadCreateInput as LoadCreateInput };
