/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Load } from "./Load";
import { LoadCountArgs } from "./LoadCountArgs";
import { LoadFindManyArgs } from "./LoadFindManyArgs";
import { LoadFindUniqueArgs } from "./LoadFindUniqueArgs";
import { CreateLoadArgs } from "./CreateLoadArgs";
import { UpdateLoadArgs } from "./UpdateLoadArgs";
import { DeleteLoadArgs } from "./DeleteLoadArgs";
import { AssignmentFindManyArgs } from "../../assignment/base/AssignmentFindManyArgs";
import { Assignment } from "../../assignment/base/Assignment";
import { NegotiationFindManyArgs } from "../../negotiation/base/NegotiationFindManyArgs";
import { Negotiation } from "../../negotiation/base/Negotiation";
import { User } from "../../user/base/User";
import { LoadService } from "../load.service";
@graphql.Resolver(() => Load)
export class LoadResolverBase {
  constructor(protected readonly service: LoadService) {}

  async _loadsMeta(
    @graphql.Args() args: LoadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Load])
  async loads(@graphql.Args() args: LoadFindManyArgs): Promise<Load[]> {
    return this.service.loads(args);
  }

  @graphql.Query(() => Load, { nullable: true })
  async load(@graphql.Args() args: LoadFindUniqueArgs): Promise<Load | null> {
    const result = await this.service.load(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Load)
  async createLoad(@graphql.Args() args: CreateLoadArgs): Promise<Load> {
    return await this.service.createLoad({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Load)
  async updateLoad(@graphql.Args() args: UpdateLoadArgs): Promise<Load | null> {
    try {
      return await this.service.updateLoad({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Load)
  async deleteLoad(@graphql.Args() args: DeleteLoadArgs): Promise<Load | null> {
    try {
      return await this.service.deleteLoad(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Assignment], { name: "assignments" })
  async findAssignments(
    @graphql.Parent() parent: Load,
    @graphql.Args() args: AssignmentFindManyArgs
  ): Promise<Assignment[]> {
    const results = await this.service.findAssignments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Negotiation], { name: "negotiations" })
  async findNegotiations(
    @graphql.Parent() parent: Load,
    @graphql.Args() args: NegotiationFindManyArgs
  ): Promise<Negotiation[]> {
    const results = await this.service.findNegotiations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Load): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
