/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LoadService } from "../load.service";
import { LoadCreateInput } from "./LoadCreateInput";
import { Load } from "./Load";
import { LoadFindManyArgs } from "./LoadFindManyArgs";
import { LoadWhereUniqueInput } from "./LoadWhereUniqueInput";
import { LoadUpdateInput } from "./LoadUpdateInput";
import { AssignmentFindManyArgs } from "../../assignment/base/AssignmentFindManyArgs";
import { Assignment } from "../../assignment/base/Assignment";
import { AssignmentWhereUniqueInput } from "../../assignment/base/AssignmentWhereUniqueInput";
import { NegotiationFindManyArgs } from "../../negotiation/base/NegotiationFindManyArgs";
import { Negotiation } from "../../negotiation/base/Negotiation";
import { NegotiationWhereUniqueInput } from "../../negotiation/base/NegotiationWhereUniqueInput";

export class LoadControllerBase {
  constructor(protected readonly service: LoadService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Load })
  async createLoad(@common.Body() data: LoadCreateInput): Promise<Load> {
    return await this.service.createLoad({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        deliveryDate: true,
        destination: true,
        details: true,
        id: true,
        origin: true,
        pickupDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        weight: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Load] })
  @ApiNestedQuery(LoadFindManyArgs)
  async loads(@common.Req() request: Request): Promise<Load[]> {
    const args = plainToClass(LoadFindManyArgs, request.query);
    return this.service.loads({
      ...args,
      select: {
        createdAt: true,
        deliveryDate: true,
        destination: true,
        details: true,
        id: true,
        origin: true,
        pickupDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        weight: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Load })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async load(
    @common.Param() params: LoadWhereUniqueInput
  ): Promise<Load | null> {
    const result = await this.service.load({
      where: params,
      select: {
        createdAt: true,
        deliveryDate: true,
        destination: true,
        details: true,
        id: true,
        origin: true,
        pickupDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        weight: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Load })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLoad(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() data: LoadUpdateInput
  ): Promise<Load | null> {
    try {
      return await this.service.updateLoad({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          deliveryDate: true,
          destination: true,
          details: true,
          id: true,
          origin: true,
          pickupDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Load })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLoad(
    @common.Param() params: LoadWhereUniqueInput
  ): Promise<Load | null> {
    try {
      return await this.service.deleteLoad({
        where: params,
        select: {
          createdAt: true,
          deliveryDate: true,
          destination: true,
          details: true,
          id: true,
          origin: true,
          pickupDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/assignments")
  @ApiNestedQuery(AssignmentFindManyArgs)
  async findAssignments(
    @common.Req() request: Request,
    @common.Param() params: LoadWhereUniqueInput
  ): Promise<Assignment[]> {
    const query = plainToClass(AssignmentFindManyArgs, request.query);
    const results = await this.service.findAssignments(params.id, {
      ...query,
      select: {
        createdAt: true,
        finalAmount: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        negotiation: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/assignments")
  async connectAssignments(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        connect: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/assignments")
  async updateAssignments(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        set: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/assignments")
  async disconnectAssignments(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        disconnect: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/negotiations")
  @ApiNestedQuery(NegotiationFindManyArgs)
  async findNegotiations(
    @common.Req() request: Request,
    @common.Param() params: LoadWhereUniqueInput
  ): Promise<Negotiation[]> {
    const query = plainToClass(NegotiationFindManyArgs, request.query);
    const results = await this.service.findNegotiations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        newAmount: true,
        proposedAmount: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/negotiations")
  async connectNegotiations(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: NegotiationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      negotiations: {
        connect: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/negotiations")
  async updateNegotiations(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: NegotiationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      negotiations: {
        set: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/negotiations")
  async disconnectNegotiations(
    @common.Param() params: LoadWhereUniqueInput,
    @common.Body() body: NegotiationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      negotiations: {
        disconnect: body,
      },
    };
    await this.service.updateLoad({
      where: params,
      data,
      select: { id: true },
    });
  }
}
