/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Negotiation } from "./Negotiation";
import { NegotiationCountArgs } from "./NegotiationCountArgs";
import { NegotiationFindManyArgs } from "./NegotiationFindManyArgs";
import { NegotiationFindUniqueArgs } from "./NegotiationFindUniqueArgs";
import { CreateNegotiationArgs } from "./CreateNegotiationArgs";
import { UpdateNegotiationArgs } from "./UpdateNegotiationArgs";
import { DeleteNegotiationArgs } from "./DeleteNegotiationArgs";
import { AssignmentFindManyArgs } from "../../assignment/base/AssignmentFindManyArgs";
import { Assignment } from "../../assignment/base/Assignment";
import { Load } from "../../load/base/Load";
import { User } from "../../user/base/User";
import { NegotiationService } from "../negotiation.service";
@graphql.Resolver(() => Negotiation)
export class NegotiationResolverBase {
  constructor(protected readonly service: NegotiationService) {}

  async _negotiationsMeta(
    @graphql.Args() args: NegotiationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Negotiation])
  async negotiations(
    @graphql.Args() args: NegotiationFindManyArgs
  ): Promise<Negotiation[]> {
    return this.service.negotiations(args);
  }

  @graphql.Query(() => Negotiation, { nullable: true })
  async negotiation(
    @graphql.Args() args: NegotiationFindUniqueArgs
  ): Promise<Negotiation | null> {
    const result = await this.service.negotiation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Negotiation)
  async createNegotiation(
    @graphql.Args() args: CreateNegotiationArgs
  ): Promise<Negotiation> {
    return await this.service.createNegotiation({
      ...args,
      data: {
        ...args.data,

        load: args.data.load
          ? {
              connect: args.data.load,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Negotiation)
  async updateNegotiation(
    @graphql.Args() args: UpdateNegotiationArgs
  ): Promise<Negotiation | null> {
    try {
      return await this.service.updateNegotiation({
        ...args,
        data: {
          ...args.data,

          load: args.data.load
            ? {
                connect: args.data.load,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Negotiation)
  async deleteNegotiation(
    @graphql.Args() args: DeleteNegotiationArgs
  ): Promise<Negotiation | null> {
    try {
      return await this.service.deleteNegotiation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Assignment], { name: "assignments" })
  async findAssignments(
    @graphql.Parent() parent: Negotiation,
    @graphql.Args() args: AssignmentFindManyArgs
  ): Promise<Assignment[]> {
    const results = await this.service.findAssignments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Load, {
    nullable: true,
    name: "load",
  })
  async getLoad(@graphql.Parent() parent: Negotiation): Promise<Load | null> {
    const result = await this.service.getLoad(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Negotiation): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
