/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NegotiationService } from "../negotiation.service";
import { NegotiationCreateInput } from "./NegotiationCreateInput";
import { Negotiation } from "./Negotiation";
import { NegotiationFindManyArgs } from "./NegotiationFindManyArgs";
import { NegotiationWhereUniqueInput } from "./NegotiationWhereUniqueInput";
import { NegotiationUpdateInput } from "./NegotiationUpdateInput";
import { AssignmentFindManyArgs } from "../../assignment/base/AssignmentFindManyArgs";
import { Assignment } from "../../assignment/base/Assignment";
import { AssignmentWhereUniqueInput } from "../../assignment/base/AssignmentWhereUniqueInput";

export class NegotiationControllerBase {
  constructor(protected readonly service: NegotiationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Negotiation })
  async createNegotiation(
    @common.Body() data: NegotiationCreateInput
  ): Promise<Negotiation> {
    return await this.service.createNegotiation({
      data: {
        ...data,

        load: data.load
          ? {
              connect: data.load,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        newAmount: true,
        proposedAmount: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Negotiation] })
  @ApiNestedQuery(NegotiationFindManyArgs)
  async negotiations(@common.Req() request: Request): Promise<Negotiation[]> {
    const args = plainToClass(NegotiationFindManyArgs, request.query);
    return this.service.negotiations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        newAmount: true,
        proposedAmount: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Negotiation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async negotiation(
    @common.Param() params: NegotiationWhereUniqueInput
  ): Promise<Negotiation | null> {
    const result = await this.service.negotiation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        newAmount: true,
        proposedAmount: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Negotiation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateNegotiation(
    @common.Param() params: NegotiationWhereUniqueInput,
    @common.Body() data: NegotiationUpdateInput
  ): Promise<Negotiation | null> {
    try {
      return await this.service.updateNegotiation({
        where: params,
        data: {
          ...data,

          load: data.load
            ? {
                connect: data.load,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          load: {
            select: {
              id: true,
            },
          },

          newAmount: true,
          proposedAmount: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Negotiation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteNegotiation(
    @common.Param() params: NegotiationWhereUniqueInput
  ): Promise<Negotiation | null> {
    try {
      return await this.service.deleteNegotiation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          load: {
            select: {
              id: true,
            },
          },

          newAmount: true,
          proposedAmount: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/assignments")
  @ApiNestedQuery(AssignmentFindManyArgs)
  async findAssignments(
    @common.Req() request: Request,
    @common.Param() params: NegotiationWhereUniqueInput
  ): Promise<Assignment[]> {
    const query = plainToClass(AssignmentFindManyArgs, request.query);
    const results = await this.service.findAssignments(params.id, {
      ...query,
      select: {
        createdAt: true,
        finalAmount: true,
        id: true,

        load: {
          select: {
            id: true,
          },
        },

        negotiation: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/assignments")
  async connectAssignments(
    @common.Param() params: NegotiationWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        connect: body,
      },
    };
    await this.service.updateNegotiation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/assignments")
  async updateAssignments(
    @common.Param() params: NegotiationWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        set: body,
      },
    };
    await this.service.updateNegotiation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/assignments")
  async disconnectAssignments(
    @common.Param() params: NegotiationWhereUniqueInput,
    @common.Body() body: AssignmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      assignments: {
        disconnect: body,
      },
    };
    await this.service.updateNegotiation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
