/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Negotiation as PrismaNegotiation,
  Assignment as PrismaAssignment,
  Load as PrismaLoad,
  User as PrismaUser,
} from "@prisma/client";

export class NegotiationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.NegotiationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.negotiation.count(args);
  }

  async negotiations(
    args: Prisma.NegotiationFindManyArgs
  ): Promise<PrismaNegotiation[]> {
    return this.prisma.negotiation.findMany(args);
  }
  async negotiation(
    args: Prisma.NegotiationFindUniqueArgs
  ): Promise<PrismaNegotiation | null> {
    return this.prisma.negotiation.findUnique(args);
  }
  async createNegotiation(
    args: Prisma.NegotiationCreateArgs
  ): Promise<PrismaNegotiation> {
    return this.prisma.negotiation.create(args);
  }
  async updateNegotiation(
    args: Prisma.NegotiationUpdateArgs
  ): Promise<PrismaNegotiation> {
    return this.prisma.negotiation.update(args);
  }
  async deleteNegotiation(
    args: Prisma.NegotiationDeleteArgs
  ): Promise<PrismaNegotiation> {
    return this.prisma.negotiation.delete(args);
  }

  async findAssignments(
    parentId: string,
    args: Prisma.AssignmentFindManyArgs
  ): Promise<PrismaAssignment[]> {
    return this.prisma.negotiation
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .assignments(args);
  }

  async getLoad(parentId: string): Promise<PrismaLoad | null> {
    return this.prisma.negotiation
      .findUnique({
        where: { id: parentId },
      })
      .load();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.negotiation
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
