/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Assignment } from "../../assignment/base/Assignment";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsNumber,
  Min,
  Max,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Load } from "../../load/base/Load";
import { EnumNegotiationStatus } from "./EnumNegotiationStatus";
import { User } from "../../user/base/User";

@ObjectType()
class Negotiation {
  @ApiProperty({
    required: false,
    type: () => [Assignment],
  })
  @ValidateNested()
  @Type(() => Assignment)
  @IsOptional()
  assignments?: Array<Assignment>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => Load,
  })
  @ValidateNested()
  @Type(() => Load)
  @IsOptional()
  load?: Load | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  newAmount!: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  proposedAmount!: number | null;

  @ApiProperty({
    required: false,
    enum: EnumNegotiationStatus,
  })
  @IsEnum(EnumNegotiationStatus)
  @IsOptional()
  @Field(() => EnumNegotiationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}

export { Negotiation as Negotiation };
