/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentCreateNestedManyWithoutNegotiationsInput } from "./AssignmentCreateNestedManyWithoutNegotiationsInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { LoadWhereUniqueInput } from "../../load/base/LoadWhereUniqueInput";
import { EnumNegotiationStatus } from "./EnumNegotiationStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class NegotiationCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentCreateNestedManyWithoutNegotiationsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentCreateNestedManyWithoutNegotiationsInput)
  @IsOptional()
  @Field(() => AssignmentCreateNestedManyWithoutNegotiationsInput, {
    nullable: true,
  })
  assignments?: AssignmentCreateNestedManyWithoutNegotiationsInput;

  @ApiProperty({
    required: false,
    type: () => LoadWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LoadWhereUniqueInput)
  @IsOptional()
  @Field(() => LoadWhereUniqueInput, {
    nullable: true,
  })
  load?: LoadWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  newAmount?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  proposedAmount?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumNegotiationStatus,
  })
  @IsEnum(EnumNegotiationStatus)
  @IsOptional()
  @Field(() => EnumNegotiationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { NegotiationCreateInput as NegotiationCreateInput };
